name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

jobs:
  depot-remote-cache:
    name: Depot with Remote Cache
    runs-on: depot-ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
      - run: ./script/linux # Install Dependencies
      - run: RUSTC_WRAPPER=sccache cargo build --release

  depot-cacheless:
    name: Depot Cacheless
    runs-on: depot-ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
      - run: ./script/linux # Install Dependencies
      - run: cargo build --release

  github-local-cache:
    name: Github with Local Cache
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
      - run: ./script/linux # Install Dependencies
      - run: cargo build --release
